completed minus tests
fjelltopp/ckanext-unaids pull request #107
Opened 2021-03-26 17:55 UTC by Manoj-nathwani

- Jira ticket https://fjelltopp.atlassian.net/browse/ADX-625
- Video of UI https://youtu.be/zo1UgaCsc5Y
- Related https://github.com/fjelltopp/adx_develop/pull/56

TODO:
- [ ] Drag+drop to work on entire page (very important)
- [ ] Progress bars showing upload progress (not absolutely required)
- [ ] Remove `ckanext-file_uploader_ui` (see https://github.com/fjelltopp/adx_develop/pull/56)
- [ ] A lot of small improvements were made to how we integrate react into ckan. It'll require a little refactoring byt these should be copied over to the `FileInputComponent`. This is a 1-2hr task max.
- [ ] Update translations `.po` file

2021-03-26 18:07 UTC, Manoj-nathwani commented
@tomeksabala This is ready for it's first PR review. I've got it to a state where it perfectly works however as it was a POC and we wanted this done asap i've taken the shortcuts mentioned above. Give it a test!

2021-04-07 15:04 UTC, Manoj-nathwani commented
![image](https://user-images.githubusercontent.com/2634482/113889208-e82e6d00-97ba-11eb-8aea-39e851f4a86a.png)

Error handling looks like this ^

2021-04-07 16:17 UTC, Manoj-nathwani commented on ckanext/unaids/react/components/BulkFileUploaderComponent/src/FileUploader.js
> +    const maxResourceSize = 5; // TODO: set up correctly
don't forget about this!

2021-04-09 16:38 UTC, Manoj-nathwani commented on ckanext/unaids/helpers.py
> +from ckanext.scheming.helpers import scheming_get_dataset_schema
No idea what this is but I seem to have added it 🤔

2021-04-13 09:31 UTC, tomeksabala requested changes

2021-04-13 09:31 UTC, tomeksabala commented on ckanext/unaids/theme/templates/package/new_resource_not_draft.html
> -  {% endif %}
Please keep this buld upload toggle in `ckanext/unaids/theme/templates/package/read_base.html`

2021-04-13 09:31 UTC, tomeksabala commented on ckanext/unaids/react/components/BulkFileUploaderComponent/src/App.js
> +export default function App({ lfsServer, maxResourceSize, orgId, datasetId, defaultFields }) {
Try to organize your react components into separate files for better readability.

2021-04-13 11:31 UTC, merged