Adx 648 request authz token before each bulked file upload
fjelltopp/ckanext-unaids pull request #112
Opened 2021-04-15 14:52 UTC by Manoj-nathwani

https://fjelltopp.atlassian.net/jira/software/projects/ADX/boards/4?selectedIssue=ADX-647

# Problem
- We were requesting the authz token before uploading any files, then recycling the same token for every file upload
- The issue is that if a user uploads 20 files, each taking 2mins to upload, then the last few files would fail to upload as the auth token would have expired

# Solution
- We now request a new auth token before uploading each file

2021-04-15 15:14 UTC, Manoj-nathwani commented
Once merged, carry out this: https://fjelltopp.atlassian.net/browse/ADX-649?focusedCommentId=10763

2021-04-16 07:14 UTC, tomeksabala requested changes
This looks good. I think it'd be worth if you consider updating one mock name (it's not direct part of this PR but it's very close in scope so let's add it here).

2021-04-16 07:14 UTC, tomeksabala commented on ckanext/unaids/react/components/BulkFileUploaderComponent/index.test.js
>    expect(mockedAxiosPost).toHaveBeenCalledTimes(
Please look at my comment to the other PR about the mock name for `mockedAxiosPost`

2021-04-16 10:38 UTC, tomeksabala approved these changes
Looks good to me! :)

2021-04-16 10:39 UTC, merged