Adx 1021 using a flash message to inform users of profile data updated
fjelltopp/ckanext-unaids pull request #287
Opened 2023-07-20 11:41 UTC by A-Souhei

## Description

Flash message after user updates his profile data through APE and back in ADR

## Checklist

Put an `x` in the boxes that apply to this pull request (you can also fill these out after opening the pull request).
You may not need to check all boxes.

- [ ] The Jira ticket for this issue has been updated to "Ready to Review" or equivalent.
- [ ] I have developed these changes in discussion with the appropriate project manager.
- [ ] My code follows the general Fjelltopp documentation (see Confluence).
- [ ] I have made corresponding changes to the Fjelltopp documentation (see Confluence).
- [ ] I have rebased this branch with master.
- [ ] New dependency changes have been committed.
- [ ] I have added automated tests that prove my fix is effective or that my feature works.
- [ ] New and existing tests pass locally with my changes.
- [ ] My changes generate no new warnings.
- [ ] I have performed a self-review of my own code.
- [ ] I have assigned at least one reviewer.

2023-07-20 12:10 UTC, tomeksabala requested changes
This looks good and let's roll out with the flash message option first as it doesn't require any further changes in the ADR configs.

Could you add translations for the newly added strings, please?

2023-08-07 14:38 UTC, kforenc approved these changes
Well done.

2023-08-07 14:39 UTC, kforenc submitted a review, later dismissed

2023-08-09 09:51 UTC, tomeksabala submitted a review, later dismissed

2023-08-09 16:53 UTC, kforenc approved these changes

2023-08-09 16:54 UTC, merged