Force users to select an autocomplete value
fjelltopp/ckanext-unaids pull request #67
Opened 2020-10-02 09:31 UTC by Manoj-nathwani

See [Jira ticket](https://fjelltopp.atlassian.net/browse/ADX-394?atlOrigin=eyJpIjoiNDhjY2I0ODUxYmQxNGQxNjkwZThjMjVjMmJhOGY3ZjkiLCJwIjoiaiJ9)

2020-10-02 11:04 UTC, tomeksabala requested changes
You should start your branch from development not master.

2020-10-02 14:16 UTC, Manoj-nathwani commented on ckanext/unaids/fanstatic/autocomplete-without-creating-new-options.js
> +this.ckan.module('autocomplete-without-creating-new-options', function (jQuery) {
I changed this line

2020-10-02 14:16 UTC, Manoj-nathwani commented on ckanext/unaids/fanstatic/autocomplete-without-creating-new-options.js
> +      settings.createSearchChoice = false;
I changed this line

2020-10-02 14:22 UTC, Manoj-nathwani commented
![image](https://user-images.githubusercontent.com/2634482/94933901-ed84c500-04c2-11eb-84d8-2ef865e1afcc.png)

Fixed the `Add Member` page too ✅

2020-10-05 12:18 UTC, Manoj-nathwani commented
Moved to https://github.com/fjelltopp/ckanext-unaids/pull/68

2020-10-05 12:18 UTC, closed without merging